// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: svc/lk-token-provider.proto

package svc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LivekitToken_Request_FullMethodName = "/camfield.svc.lk_token_provider.LivekitToken/Request"
)

// LivekitTokenClient is the client API for LivekitToken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LivekitTokenClient interface {
	Request(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoomTokenReply, error)
}

type livekitTokenClient struct {
	cc grpc.ClientConnInterface
}

func NewLivekitTokenClient(cc grpc.ClientConnInterface) LivekitTokenClient {
	return &livekitTokenClient{cc}
}

func (c *livekitTokenClient) Request(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoomTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomTokenReply)
	err := c.cc.Invoke(ctx, LivekitToken_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LivekitTokenServer is the server API for LivekitToken service.
// All implementations must embed UnimplementedLivekitTokenServer
// for forward compatibility.
type LivekitTokenServer interface {
	Request(context.Context, *Empty) (*RoomTokenReply, error)
	mustEmbedUnimplementedLivekitTokenServer()
}

// UnimplementedLivekitTokenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLivekitTokenServer struct{}

func (UnimplementedLivekitTokenServer) Request(context.Context, *Empty) (*RoomTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedLivekitTokenServer) mustEmbedUnimplementedLivekitTokenServer() {}
func (UnimplementedLivekitTokenServer) testEmbeddedByValue()                      {}

// UnsafeLivekitTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LivekitTokenServer will
// result in compilation errors.
type UnsafeLivekitTokenServer interface {
	mustEmbedUnimplementedLivekitTokenServer()
}

func RegisterLivekitTokenServer(s grpc.ServiceRegistrar, srv LivekitTokenServer) {
	// If the following call pancis, it indicates UnimplementedLivekitTokenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LivekitToken_ServiceDesc, srv)
}

func _LivekitToken_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivekitTokenServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LivekitToken_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivekitTokenServer).Request(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LivekitToken_ServiceDesc is the grpc.ServiceDesc for LivekitToken service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LivekitToken_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "camfield.svc.lk_token_provider.LivekitToken",
	HandlerType: (*LivekitTokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _LivekitToken_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc/lk-token-provider.proto",
}
