// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: svc/room-manager.proto

package svc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomManager_Request_FullMethodName = "/sphinx.camfield.svc.RoomManager/Request"
)

// RoomManagerClient is the client API for RoomManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomManagerClient interface {
	Request(ctx context.Context, in *RoomTokenRequest, opts ...grpc.CallOption) (*RoomTokenReply, error)
}

type roomManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomManagerClient(cc grpc.ClientConnInterface) RoomManagerClient {
	return &roomManagerClient{cc}
}

func (c *roomManagerClient) Request(ctx context.Context, in *RoomTokenRequest, opts ...grpc.CallOption) (*RoomTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomTokenReply)
	err := c.cc.Invoke(ctx, RoomManager_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomManagerServer is the server API for RoomManager service.
// All implementations must embed UnimplementedRoomManagerServer
// for forward compatibility.
type RoomManagerServer interface {
	Request(context.Context, *RoomTokenRequest) (*RoomTokenReply, error)
	mustEmbedUnimplementedRoomManagerServer()
}

// UnimplementedRoomManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomManagerServer struct{}

func (UnimplementedRoomManagerServer) Request(context.Context, *RoomTokenRequest) (*RoomTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedRoomManagerServer) mustEmbedUnimplementedRoomManagerServer() {}
func (UnimplementedRoomManagerServer) testEmbeddedByValue()                     {}

// UnsafeRoomManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomManagerServer will
// result in compilation errors.
type UnsafeRoomManagerServer interface {
	mustEmbedUnimplementedRoomManagerServer()
}

func RegisterRoomManagerServer(s grpc.ServiceRegistrar, srv RoomManagerServer) {
	// If the following call pancis, it indicates UnimplementedRoomManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomManager_ServiceDesc, srv)
}

func _RoomManager_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagerServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomManager_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagerServer).Request(ctx, req.(*RoomTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomManager_ServiceDesc is the grpc.ServiceDesc for RoomManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sphinx.camfield.svc.RoomManager",
	HandlerType: (*RoomManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _RoomManager_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc/room-manager.proto",
}
