// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: events/room.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceAssigned struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Room   string `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *DeviceAssigned) Reset() {
	*x = DeviceAssigned{}
	mi := &file_events_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAssigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAssigned) ProtoMessage() {}

func (x *DeviceAssigned) ProtoReflect() protoreflect.Message {
	mi := &file_events_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAssigned.ProtoReflect.Descriptor instead.
func (*DeviceAssigned) Descriptor() ([]byte, []int) {
	return file_events_room_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceAssigned) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DeviceAssigned) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type DeviceRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Room   string `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *DeviceRemoved) Reset() {
	*x = DeviceRemoved{}
	mi := &file_events_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRemoved) ProtoMessage() {}

func (x *DeviceRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_events_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRemoved.ProtoReflect.Descriptor instead.
func (*DeviceRemoved) Descriptor() ([]byte, []int) {
	return file_events_room_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceRemoved) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DeviceRemoved) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

var File_events_room_proto protoreflect.FileDescriptor

var file_events_room_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x73, 0x70, 0x68, 0x69, 0x6e, 0x78, 0x2e, 0x63, 0x61, 0x6d, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x0e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x3b, 0x0a, 0x0d, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x68, 0x69, 0x6e, 0x78, 0x2d, 0x63, 0x61, 0x6d, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_room_proto_rawDescOnce sync.Once
	file_events_room_proto_rawDescData = file_events_room_proto_rawDesc
)

func file_events_room_proto_rawDescGZIP() []byte {
	file_events_room_proto_rawDescOnce.Do(func() {
		file_events_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_room_proto_rawDescData)
	})
	return file_events_room_proto_rawDescData
}

var file_events_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_room_proto_goTypes = []any{
	(*DeviceAssigned)(nil), // 0: sphinx.camfield.events.DeviceAssigned
	(*DeviceRemoved)(nil),  // 1: sphinx.camfield.events.DeviceRemoved
}
var file_events_room_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_room_proto_init() }
func file_events_room_proto_init() {
	if File_events_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_room_proto_goTypes,
		DependencyIndexes: file_events_room_proto_depIdxs,
		MessageInfos:      file_events_room_proto_msgTypes,
	}.Build()
	File_events_room_proto = out.File
	file_events_room_proto_rawDesc = nil
	file_events_room_proto_goTypes = nil
	file_events_room_proto_depIdxs = nil
}
